# Generated by Django 3.1.6 on 2021-02-11 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome')),
                ('telefone', models.CharField(max_length=11, verbose_name='Nome')),
            ],
        ),
        migrations.CreateModel(
            name='ProdutoServico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=150, verbose_name='Descrição')),
                ('codigo_barras', models.IntegerField(verbose_name='Código de Barras')),
                ('preco_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Preço Unitário')),
                ('comissao', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='% Comissão')),
            ],
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome')),
                ('telefone', models.CharField(max_length=11, verbose_name='Nome')),
            ],
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now=True, verbose_name='Data criação')),
                ('situacao', models.IntegerField(choices=[(1, 'Aberto'), (2, 'Finalizado'), (3, 'Cancelado')], default=1, verbose_name='Situação')),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Total Venda')),
                ('valor_comissao_total', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Valor Total de Comissão')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adm.cliente', verbose_name='Cliente')),
                ('vendedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='adm.vendedor', verbose_name='Vendedor')),
            ],
        ),
        migrations.CreateModel(
            name='ItemVenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(default=1, verbose_name='Quantidade')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total')),
                ('total_comissao', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Total de Comissão')),
                ('produto_servico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adm.produtoservico', verbose_name='Produto/Serviço')),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adm.venda', verbose_name='Venda')),
            ],
        ),
    ]
